# Source: jxboot-helmfile-resources/templates/build-bot-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "tekton-bot"
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::153787536644:role/tf-cf-eks-cluster-tekton-bot
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
secrets:
  - name: tekton-container-registry-auth
  - name: tekton-git
