apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-cf-eks-cluster
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "153787536644"
    provider: eks
    region: us-east-1
    registry: 153787536644.dkr.ecr.us-east-1.amazonaws.com
  environments:
  - key: dev
    owner: rackerlabs
    repository: jx3-eks-asm
  - key: staging
  - key: production
  ingress:
    domain: 44.206.107.204.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: PaulRepo
  repository: nexus
  secretStorage: secretsManager
  storage:
  - name: logs
    url: s3://logs-tf-cf-eks-cluster-20220630080842722200000007
  - name: reports
    url: s3://reports-tf-cf-eks-cluster-20220630080842724400000008
  - name: repository
    url: s3://repository-tf-cf-eks-cluster-20220630080842725900000009
  terraform: true
  vault: {}
  webhook: lighthouse
